# Generated by Django 4.2 on 2024-12-16 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_address', models.CharField(max_length=255)),
                ('facility_city', models.CharField(max_length=100)),
                ('facility_state', models.CharField(max_length=100)),
                ('facility_zip', models.CharField(max_length=20)),
                ('pe_description', models.CharField(choices=[('RESTAURANT (0-30) SEATS MODERATE RISK', 'RESTAURANT (0-30) SEATS MODERATE RISK'), ('RESTAURANT (0-30) SEATS HIGH RISK', 'RESTAURANT (0-30) SEATS HIGH RISK'), ('RESTAURANT (0-30) SEATS LOW RISK', 'RESTAURANT (0-30) SEATS LOW RISK'), ('RESTAURANT (31-60) SEATS MODERATE RISK', 'RESTAURANT (31-60) SEATS MODERATE RISK'), ('RESTAURANT (31-60) SEATS HIGH RISK', 'RESTAURANT (31-60) SEATS HIGH RISK'), ('RESTAURANT (31-60) SEATS LOW RISK', 'RESTAURANT (31-60) SEATS LOW RISK'), ('RESTAURANT (61-150) SEATS MODERATE RISK', 'RESTAURANT (61-150) SEATS MODERATE RISK'), ('RESTAURANT (61-150) SEATS HIGH RISK', 'RESTAURANT (61-150) SEATS HIGH RISK'), ('RESTAURANT (61-150) SEATS LOW RISK', 'RESTAURANT (61-150) SEATS LOW RISK'), ('RESTAURANT (150+) SEATS MODERATE RISK', 'RESTAURANT (150+) SEATS MODERATE RISK'), ('RESTAURANT (150+) SEATS HIGH RISK', 'RESTAURANT (150+) SEATS HIGH RISK'), ('RESTAURANT (150+) SEATS LOW RISK', 'RESTAURANT (150+) SEATS LOW RISK')], max_length=255)),
                ('program_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('predicted_revenue', models.FloatField(blank=True, null=True, verbose_name='Revenue Prédit')),
                ('seating_capacity', models.IntegerField(blank=True, null=True, verbose_name="Capacité d'Accueil")),
                ('average_meal_price', models.FloatField(blank=True, null=True, verbose_name="Prix Moyen d'un Repas")),
                ('marketing_budget', models.IntegerField(blank=True, null=True, verbose_name='Budget Marketing')),
                ('weekend_reservations', models.IntegerField(blank=True, null=True, verbose_name='Réservations du Weekend')),
                ('weekday_reservations', models.IntegerField(blank=True, null=True, verbose_name='Réservations en Semaine')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
    ]
